# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*" # Triggers workflow on version tags (e.g., v1.0.0)

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.1' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Init
      run: go mod init nims-webhook

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -o nims-webhook-${{ github.ref_name }} nims-webhook.go
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nims-webhook-${{ github.ref_name }}
        path: ./nims-webhook-${{ github.ref_name }}
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: nims-webhook-${{ github.ref_name }}
        body: |
          This release includes the binary for nims-webhook ${{ github.ref_name }}.
        draft: false
        prerelease: false

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nims-webhook-${{ github.ref_name }}
        asset_name: nims-webhook-${{ github.ref_name }}
        asset_content_type: application/octet-stream
