# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.1' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Init
      run: go mod init nims-webhook

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -o nims-webhook-${{ matrix.go-version }} nims-webhook.go
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nims-webhook-${{ matrix.go-version }}
        path: ./nims-webhook-${{ matrix.go-version }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
  
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
  
    - name: Install GitHub CLI
      run: sudo apt-get install -y gh
      
    - name: Delete Existing Release and Tag if Exists
      run: |
        if gh release view ${{ github.ref_name }} 2>/dev/null; then
          gh release delete ${{ github.ref_name }} --yes
          git tag -d ${{ github.ref_name }}
          git push https://shortstack:${{ secrets.TOKEN }}@github.com/shortstack/nims-webhook.git :refs/tags/${{ github.ref_name }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: nims-webhook-${{ github.ref_name }}
        draft: false
        prerelease: false
  
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/nims-webhook-*
        asset_name: nims-webhook-${{ github.ref_name }}-${{ github.run_number }}
        asset_content_type: application/octet-stream

