# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*" # Triggers workflow on version tags (e.g., v1.0.0)

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.1' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Init
      run: go mod init nims-webhook

    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -o nims-webhook-${{ github.ref_name }} nims-webhook.go
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nims-webhook-${{ github.ref_name }}
        path: ./nims-webhook-${{ github.ref_name }}
